{
  release: { branches: ["master"] },
  plugins:
    [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/github",
      ["@semantic-release/npm", { "npmPublish": true }],
      ["@semantic-release/git", { "assets": ["package.json"] }],
    ],
}
